swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "MeetUp Project"
  termsOfService: "http://localhost:8080"
  contact:
    email: "juarez.lucasdaniel@gmail.com"
host: "localhost:8080"
basePath: "/meetUp"
tags:
- name: "Guest"
  description: ""
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /guest:
    post:
      tags:
      - "Guest"
      summary: "Crear y/o modificar invitados."
      description: ""
      operationId: "addGuest"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Guest"
      responses:
        "200":
          description: "Successful Operation"
        "400":
          description: "Bad Request"
          schema:
            $ref: "#/definitions/FormatError"
        "401":
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/FormatError"
        "403":
          description: "Forbidden"
          schema:
            $ref: "#/definitions/FormatError"
        "404":
          description: "Not Found"
          schema:
            $ref: "#/definitions/FormatError"
        "405":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/FormatError"
        "408":
          description: "Request Tiemout"
          schema:
            $ref: "#/definitions/FormatError"
        "418":
          description: "Controlled Error"
          schema:
            $ref: "#/definitions/FormatError"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/FormatError"
      security:
      - room_auth:
        - "write:guest"
        - "read:guest"
  /guest/{roomId}:
    get:
      tags:
      - "Guest"
      summary: "Consultar datos de invitados."
      description: ""
      operationId: "getGuest"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "roomId"
        in: "path"
        description: "Identificador de la sala"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Guest"
        "400":
          description: "Bad Request"
          schema:
            $ref: "#/definitions/FormatError"
        "401":
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/FormatError"
        "403":
          description: "Forbidden"
          schema:
            $ref: "#/definitions/FormatError"
        "404":
          description: "Not Found"
          schema:
            $ref: "#/definitions/FormatError"
        "405":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/FormatError"
        "408":
          description: "Request Tiemout"
          schema:
            $ref: "#/definitions/FormatError"
        "418":
          description: "Controlled Error"
          schema:
            $ref: "#/definitions/FormatError"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/FormatError"
      security:
      - room_auth:
        - "write:guest"
        - "read:guest"
  /meetingGuest/{id}:
    delete:
      tags:
      - "Guest"
      summary: "Eliminar un invitado."
      description: ""
      operationId: "deleteRoom"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "id"
        in: "path"
        description: "Identificador de la sala"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful Operation"
        "400":
          description: "Bad Request"
          schema:
            $ref: "#/definitions/FormatError"
        "401":
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/FormatError"
        "403":
          description: "Forbidden"
          schema:
            $ref: "#/definitions/FormatError"
        "404":
          description: "Not Found"
          schema:
            $ref: "#/definitions/FormatError"
        "405":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/FormatError"
        "408":
          description: "Request Tiemout"
          schema:
            $ref: "#/definitions/FormatError"
        "418":
          description: "Controlled Error"
          schema:
            $ref: "#/definitions/FormatError"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/FormatError"
      security:
      - room_auth:
        - "write:guest"
        - "read:guest"
securityDefinitions:
  room_auth:
    type: "oauth2"
    authorizationUrl: "http://localhost:8080/oauth/token"
    flow: "implicit"
    scopes:
      write:guest: "modify guest in your account"
      read:guest: "read your guest"
definitions:
  Guest:
    type: "object"
    required:
    - "roomId"
    - "guest"
    properties:
      id:
        type: "integer"
        format: "int64"
      roomId:
        type: "string"
        description: "Alfanumérico que identifica la sala (lo generá el backend)."
      guest:
        type: "array"
        items:
           $ref: "#/definitions/GuestDetail"
  GuestDetail:
    type: "object"
    required:
    - "name"
    - "surname"
    - "email"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        description: "Nombre del invitado."
      surname:
        type: "string"
        description: "Apellido del invitado."
      email:
        type: "string"
        description: "Email del invitado."
  FormatError:
    type: "object"
    properties:
      timestamp:
        type: "string"
        format: "date-time"
      status:
        type: "integer"
        format: "int32"
      error:
        type: "string"
      trace:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"