CREATE TABLE `guest_header` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ROOM_ID` varchar(50) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_bin